version: "3"
services:
    www:
        build: .
        volumes:
            - persistance_one:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./assets:/usr/share/nginx/html/assets:ro
        networks:
            - default
        environment:
            # NGINX-PROXY ENVIRONMENT VARIABLES
            - VIRTUAL_HOST=ms-ai-image-generator.saifs.ai
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=ms-ai-image-generator.saifs.ai
            - LETSENCRYPT_EMAIL=multiple.words.one@gmail.com
            # Application specific environment variables
            - NODE_ENV=production
        expose:
            - 80

volumes:
    persistance_one:

networks:
    default:
        external:
            name: nginx-proxy 