version: "1"
services:
  www:
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=ms-words-music-generator.saifs.ai
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ms-words-music-generator.saifs.ai
      - LETSENCRYPT_EMAIL=multiple.words.one@gmail.com
      - NODE_ENV=production
    networks:
      - default
    expose:
      - 80

  app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - www
    networks:
      - default

networks:
  default:
    external:
      name: nginx-proxy